import { assets } from "../../image/assets";


const ExpProducts = [
  {
    id: 13,
    title: "Book name",
    price: 100,
    image: `${assets.book1}`,
    reviews: 35,
    rating: 4,
    isNew: false,
    addToCart: true,
  },
  {
    id: 14,
    title: "Book name",
    price: 360,
    image:  `${assets.book1}`,
    reviews: 95,
    rating: 4.5,
    isNew: false,
    addToCart: true,
  },
  {
    id: 15,
    title: "Book name",
    price: 700,
    image:  `${assets.book1}`,
    reviews: 325,
    rating: 4,
    isNew: false,
    addToCart: true,
  },
  {
    id: 16,
    title: "Book name",
    price: 500,
    image:  `${assets.book1}`,
    reviews: 145,
    rating: 4,
    isNew: false,
    addToCart: true,
  },
  {
    id: 17,  
    title: "Book name",
    price: 960,
    image:  `${assets.book1}`,
    reviews: 85,
    rating: 4,
    isNew: true,
    addToCart: true,
  },
  {
    id: 18,
    title: "Book name",
    price: 1160,
    image:  `${assets.book1}`,
    reviews: 35,
    rating: 3.5,
    isNew: false,
    addToCart: true,
  },
  {
    id:  19,
    title: "Book name",
    price: 660,
    image:  `${assets.book1}`,
    reviews: 55,
    rating: 4,
    isNew: true,
    addToCart: true,
  },
  {
    id: 20,
    title: "Book name",
    price: 660,
    image:  `${assets.book1}`,
    reviews: 55,
    rating: 4,
    isNew: false,
    addToCart: true,
  },
];

export default ExpProducts;
